version: '3'
networks:
  micro-net:
    external: true
services:
  wish-framework-portal-dev:
    container_name: wish-framework-portal-dev
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile-dev
    image: wish-framework-portal-dev:latest
    user: ${BUILDUID:-1000}:${BUILDGID:-1000}
    environment:
      - "DOCKER_USER=${USER:-app}"
    hostname: "$USER"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../../:/home/app/wish-framework-portal/
      - nginx:/etc/nginx
    networks:
      micro-net:
        ipv4_address: 192.168.100.2
    command:
      - /bin/bash
      - -c
      - cd /home/app/wish-framework-portal && while true ; do sleep 3600; done
volumes:
  nginx:
