version: '3'
networks:
  micro-net:
    external: true
services:
  nginx-ui:
    container_name: nginx-ui
    build: .
    image: nginx-ui:latest
    user: ${BUILDUID:-1000}:${BUILDGID:-1000}
    environment:
      - "DOCKER_USER=${USER:-app}"
    hostname: "$USER"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./app:/home/app/nginx-ui/app
      - nginx:/etc/nginx
    networks:
      micro-net:
        ipv4_address: 192.168.100.2
    command:
      - /bin/bash
      - -c
      - sudo service nginx start && sudo python2 /home/app/marlon-tools/tools/dnsproxy/dnsproxy.py -s 127.0.0.11 -H 0.0.0.0 --hosts-file=/home/app/nginx-ui/app/backend/config/hosts && while true ; do sleep 3600; done
volumes:
  nginx:
